# Generated by Django 5.1.15 on 2026-10-06 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Kullanıcı Adı')),
                ('telegram_chat_id', models.CharField(blank=True, help_text="Telegram botundan bildirim almak için Chat ID'niz", max_length=50, null=True, verbose_name='Telegram Chat ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Kullanıcı Profili',
                'verbose_name_plural': 'Kullanıcı Profilleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Örn: Kırmızı Hasarsız Clio, Kadıköy 2+1 Daire', max_length=150, verbose_name='Alarm Başlığı')),
                ('category', models.CharField(choices=[('vasita', '🚗 Vasıta (Otomobil / Araç)'), ('emlak', '🏠 Emlak (Konut / Kiralık / Satılık)'), ('ikinci_el', '📱 İkinci El & Alışveriş')], default='vasita', max_length=30, verbose_name='Kategori')),
                ('search_url', models.URLField(help_text="Sahibinden'de arama yapıp kopyaladığınız filtrelenmiş arama linki", max_length=500, verbose_name="Sahibinden Arama URL'i")),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Min Fiyat (TL)')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Max Fiyat (TL)')),
                ('keywords', models.TextField(blank=True, help_text='Virgülle ayırın (Örn: kırmızı, otomatik, boyasız, balkonlu)', null=True, verbose_name='Aranan Kelimeler (Pozitif Filtre)')),
                ('negative_keywords', models.TextField(blank=True, help_text='Virgülle ayırın (Örn: ağır hasar, pert, taksi çıkması, bodrum kat)', null=True, verbose_name='İstenmeyen Kelimeler (Negatif Filtre)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Alarm Aktif mi?')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Son Tarama Zamanı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='listings.userprofile', verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Arama Kriteri (Alarm)',
                'verbose_name_plural': 'Arama Kriterleri (Alarmlar)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=50, verbose_name='Sahibinden İlan No')),
                ('title', models.CharField(max_length=255, verbose_name='İlan Başlığı')),
                ('price', models.CharField(max_length=50, verbose_name='Fiyat')),
                ('location', models.CharField(blank=True, max_length=150, null=True, verbose_name='Konum / Şehir')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Kapak Görseli Linki')),
                ('listing_url', models.URLField(max_length=500, verbose_name='Doğrudan İlan Linki')),
                ('published_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='Yayınlanma Tarihi')),
                ('is_notified', models.BooleanField(default=False, verbose_name='Bildirim Gönderildi mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sisteme Eklenme Tarihi')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='listings.searchtarget', verbose_name='Arama Hedefi')),
            ],
            options={
                'verbose_name': 'Eşleşen İlan',
                'verbose_name_plural': 'Eşleşen İlanlar',
                'ordering': ['-created_at'],
                'unique_together': {('target', 'external_id')},
            },
        ),
    ]
