# Generated by Django 6.1.1 on 2026-09-27 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(default='bi-tag', max_length=50, verbose_name='İkon (Bootstrap/Heroicon)')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='İlan Başlığı')),
                ('description', models.TextField(blank=True, verbose_name='İlan Açıklaması')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Fiyat (TL)')),
                ('city', models.CharField(max_length=100, verbose_name='İl')),
                ('district', models.CharField(max_length=100, verbose_name='İlçe')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Mahalle / Semt')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='İlan Görseli URL')),
                ('source_url', models.URLField(blank=True, max_length=500, verbose_name='Sahibinden / Kaynak İlan Linki')),
                ('specs', models.JSONField(blank=True, default=dict, verbose_name='Teknik Özellikler / Parametreler')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Görüntülenme Sayısı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='listings.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'İlan',
                'verbose_name_plural': 'İlanlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Misafir Oturumu')),
                ('title', models.CharField(max_length=150, verbose_name='Arayış Başlığı (Örn: Kadıköy 2+1 Ev)')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Minimum Bütçe (TL)')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Maksimum Bütçe (TL)')),
                ('target_city', models.CharField(blank=True, max_length=100, verbose_name='Hedef İl')),
                ('target_district', models.CharField(blank=True, max_length=100, verbose_name='Hedef İlçe')),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name='Önemli Anahtar Kelimeler (virgülle)')),
                ('preferred_specs', models.JSONField(blank=True, default=dict, verbose_name='Tercih Edilen Parametreler')),
                ('priority', models.CharField(choices=[('balanced', 'Dengeli (Fiyat + Konum + Özellikler)'), ('price', 'Öncelik: Uygun Fiyat & Bütçe'), ('location', 'Öncelik: Konum & Lokasyon'), ('specs', 'Öncelik: Donanım & Özel Nitelikler')], default='balanced', max_length=20, verbose_name='Öncelik Durumu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='listings.category', verbose_name='Aranan Kategori')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Arayış Profili',
                'verbose_name_plural': 'Kullanıcı Arayış Profilleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Misafir Oturumu')),
                ('action_type', models.CharField(choices=[('favorite', 'Favoriye Eklendi'), ('dismiss', 'İlgilenmiyorum / Gizle'), ('clicked', 'İlana Göz Atıldı')], max_length=20, verbose_name='Etkileşim Türü')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='listings.listing', verbose_name='İlan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_interactions', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'İlan Etkileşimi',
                'verbose_name_plural': 'İlan Etkileşimleri',
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'listing', 'action_type'), name='unique_user_listing_action'), models.UniqueConstraint(condition=models.Q(('session_key__isnull', False)), fields=('session_key', 'listing', 'action_type'), name='unique_session_listing_action')],
            },
        ),
    ]
