# Generated by Django 5.1.15 on 2026-10-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedlisting',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, verbose_name='İlan Özellikleri'),
        ),
        migrations.AddField(
            model_name='searchtarget',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Şehir / İl'),
        ),
        migrations.AddField(
            model_name='searchtarget',
            name='filter_criteria',
            field=models.JSONField(blank=True, default=dict, verbose_name='Gelişmiş Kriterler (JSON)'),
        ),
        migrations.AddField(
            model_name='searchtarget',
            name='town',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İlçe'),
        ),
        migrations.AlterField(
            model_name='searchtarget',
            name='keywords',
            field=models.TextField(blank=True, help_text='Virgülle ayırın (Örn: kırmızı, hatasız, boyasız, panaromik cam tavan)', null=True, verbose_name='Aranan Kelimeler (Pozitif Filtre)'),
        ),
        migrations.AlterField(
            model_name='searchtarget',
            name='search_url',
            field=models.URLField(blank=True, help_text='Doğrudan filtrelenmiş arama linki veya otomatik üretilen sorgu linki', max_length=1000, null=True, verbose_name="Sahibinden Arama URL'i"),
        ),
        migrations.AlterField(
            model_name='searchtarget',
            name='title',
            field=models.CharField(help_text='Örn: Kırmızı Hasarsız Clio 2020, Kadıköy 2+1 Balkonlu Daire', max_length=150, verbose_name='Alarm Başlığı'),
        ),
    ]
