# Generated by Django 6.1.1 on 2026-09-27 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_verified',
            field=models.BooleanField(default=True, verbose_name='Tescilli / Doğrulanmış İlan mı?'),
        ),
        migrations.AddField(
            model_name='listing',
            name='market_price_diff',
            field=models.CharField(blank=True, default='Piyasa Fiyatında', max_length=100, verbose_name='Piyasa Fiyat Kıyaslaması (Örn: Piyasanın %10 Altında)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='verification_badges',
            field=models.JSONField(blank=True, default=list, verbose_name='Tescil Rozetleri (Örn: Tapu Doğrulandı, Ekspertiz Onaylı, Piyasa Fiyatı Test Edildi)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='verification_score',
            field=models.PositiveSmallIntegerField(default=95, verbose_name='Doğruluk & Güven Puanı (%0-100)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='bi-tag', max_length=50, verbose_name='İkon'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Sahibinden İlan Linki'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='specs',
            field=models.JSONField(blank=True, default=dict, verbose_name='Teknik Parametreler'),
        ),
        migrations.AlterField(
            model_name='listinginteraction',
            name='action_type',
            field=models.CharField(choices=[('favorite', 'Favoriye Eklendi'), ('dismiss', 'İlgilenmiyorum'), ('clicked', 'İlana Göz Atıldı')], max_length=20, verbose_name='Etkileşim'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='listings.category', verbose_name='Aranan Kategori'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='Anahtar Kelimeler'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Max Bütçe'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Min Bütçe'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_specs',
            field=models.JSONField(blank=True, default=dict, verbose_name='Parametreler'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='priority',
            field=models.CharField(choices=[('balanced', 'Dengeli (Fiyat + Konum + Özellikler)'), ('price', 'Öncelik: Uygun Fiyat & Bütçe'), ('location', 'Öncelik: Konum & Lokasyon'), ('specs', 'Öncelik: Donanım & Nitelikler')], default='balanced', max_length=20, verbose_name='Öncelik'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Arayış Başlığı'),
        ),
    ]
