# Generated by Django 6.1.1 on 2026-09-28 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_is_verified_listing_market_price_diff_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Misafir Oturumu')),
                ('feedback_type', models.CharField(choices=[('positive', 'Faydalı Buldum (👍)'), ('negative', 'Yetersiz/Hatalı (👎)')], max_length=10, verbose_name='Geri Bildirim')),
                ('user_query', models.TextField(blank=True, default='', verbose_name='Kullanıcı Sorusu')),
                ('bot_reply', models.TextField(blank=True, default='', verbose_name='Bot Cevabı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Chatbot Geri Bildirimi',
                'verbose_name_plural': 'Chatbot Geri Bildirimleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
